---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1vh6c29ts8efxxgd94y3x42wvxfkpf60a6xtrvkcegwk9vs485ftqly0l7l"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1vh6c29ts8efxxgd94y3x42wvxfkpf60a6xtrvkcegwk9vs485ftqly0l7l"
stores:
  yaml:
    indent: 2
