# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:FjfLjtWIsWoCwomwTPdvUx/JpNC0w3O0Dl42BMzKdanSIE3nTET6Pg==,iv:DSUBY3mffl0LU/iaDJGqA8tq1CjZ5zm9oEdL9ciC4zg=,tag:usZ9Aa/L1xxMGsW/oPWRGg==,type:str]
sops:
  age:
    - recipient: age1vh6c29ts8efxxgd94y3x42wvxfkpf60a6xtrvkcegwk9vs485ftqly0l7l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycmdkVDdFUWo4emZnamNF
        S1BiQmFHU0FaQlFXV2JrdG1kQXIycGVNS1g0Ck5jVWloZnpycEFoWTNQLzAzbEpI
        QVF4MEJYN09vYzg3ZnBTaTRKU1EybVkKLS0tIDdtc0NPenlheHFLN3NCVjhHWFA3
        Z2IzbmNUVjZ0RGFxWTNXT09RZkJ3OEEKod80ABEEsMulOtRiCXcbr6o7qZepIQE7
        RW0uGd6I6q5IsgHQsWsyuOarSPKsnCnWjUbDMINC21wTltUF4JB/4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-12T17:13:27Z"
  mac: ENC[AES256_GCM,data:E7Wkb3dcz5AH/BZJGkA7SVmp6Xst7X/Dnr8JgumFtBZiDJuItq5XsFbD3olLCixcm1/rFpPLc16ejfWVIAxIP3LCG3VhB0GZkO95WU2/AeTaIXgtUKr1jSvnDJNGUOL9OvzhpUaYlBJ1kLm7t7aV7jsMDlkeJCgvTBgo+od/Tto=,iv:mhADNDY4FIW2Kcnu1JuC4merjoLSfS4GoA982D33GN0=,tag:w9zWrfaKf69RTqMHji73og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
