---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: network
spec:
  interval: 1h
  chartRef:
    kind: HelmRepository
    name: cowboysysop
    chart: whoami
    version: 6.0.0
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    service:
      port: 80
    image:
      repository: containous/whoami
      tag: 1.6.0
